### ISSUE TITLE
Not updated podspec

### ISSUE THREAD

**Issue by rollacode** [voxeet/voxeet-sdk-ios#23]
Looks like library was updated but podspec isn't

Pod::Spec.new do |spec|
  spec.name = "VoxeetSDK"
  spec.version = "2.4.0" **<< 2.4.1**
  spec.summary = "Voxeet provides a platform for unified communications and collaboration."
  spec.license = "MIT"
  spec.author = "Voxeet"
  spec.homepage = "https://dolby.io"
  spec.platform = :ios, "9.0"
  spec.swift_version = "5.2.4"
  spec.source = { :http => "https://vox-ios-sdk.s3.us-east-1.amazonaws.com/sdk/ios/release/#{spec.version}/VoxeetSDK.zip" } 
  spec.vendored_frameworks = "VoxeetSDK.framework", "WebRTC.framework"
end

**Comment by VTCoco** [comment]
Changelog: https://github.com/voxeet/voxeet-sdk-ios/releases/tag/v2.4.1

Support for the simulator & CocoaPods has been temporarily removed due to new Xcode architectures behaviour. CocoaPods isn't ready yet and just implement Xcode 12 support in a beta (https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0.beta.1).

This will be fixed in a later version, for now we recommend using Carthage or manually importing the SDK into your project.

**Comment by VTCoco** [comment]
Hello, we found a solution to publish our podspec without simulators architectures for Xcode 12.

So the VoxeetSDK is therefore again compatible with CocoaPods 👍

**Comment by VTCoco** [comment]
Tested with CocoaPods v1.10.0.rc.1 _(it should work the same with v1.9.3)_.

**Comment by rollacode** [comment]
Cool, tks!! 👍
